import { Product } from "./ProductCard";

export const featuredProducts: Product[] = [
  {
    id: 1,
    productUrl: "/urun/1",
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    image: "/product1.jpg",
    brand: "Ami Paris",
    brandName: "Ami Paris",
    name: "Siyah Organik Pamuk T-shirt",
    displayName: "Siyah Organik Pamuk T-shirt",
    price: 11450,
    actualPrice: 11450,
    originalPrice: 11450,
    hasDiscount: false,
  },
  {
    id: 2,
    productUrl: "/urun/2",
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    image: "/product1.jpg",
    brand: "Beymen Club",
    brandName: "Beymen Club",
    name: "Comfort Fit Siyah Oxford Gömlek",
    displayName: "Comfort Fit Siyah Oxford Gömlek",
    price: 4499,
    originalPrice: 4499,
    actualPrice: 3149.3,
    discountedPrice: 3149.3,
    secondPrice: 3149.3,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
  },
  {
    id: 3,
    productUrl: "/urun/3",
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    image: "/product1.jpg",
    brand: "Beymen Club",
    brandName: "Beymen Club",
    name: "Comfort Fit Haki Oxford Gömlek",
    displayName: "Comfort Fit Haki Oxford Gömlek",
    price: 4499,
    originalPrice: 4499,
    actualPrice: 3149.3,
    discountedPrice: 3149.3,
    secondPrice: 3149.3,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
    productPromotions: [
      {
        campaignTitle: "3 ve üzeri %30",
        promotedPrice: 3149.3,
        promotedPriceText: "3.149,30 ₺",
        showPrice: true,
      },
    ],
  },
  {
    id: 4,
    productUrl: "/urun/4",
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    image: "/product1.jpg",
    brand: "Beymen Club",
    brandName: "Beymen Club",
    name: "Comfort Fit Haki Polo Sweatshirt",
    displayName: "Comfort Fit Haki Polo Sweatshirt",
    price: 5450,
    originalPrice: 5450,
    actualPrice: 3815,
    discountedPrice: 3815,
    secondPrice: 3815,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
  },
  {
    id: 5,
    productUrl: "/urun/5",
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    image: "/product1.jpg",
    brand: "Premium Collection",
    brandName: "Premium Collection",
    name: "Klasik Pırlanta Yüzük",
    displayName: "Klasik Pırlanta Yüzük",
    price: 25000,
    actualPrice: 25000,
    originalPrice: 25000,
    hasDiscount: false,
  },
  {
    id: 6,
    productUrl: "/urun/6",
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    image: "/product1.jpg",
    brand: "Luxury Line",
    brandName: "Luxury Line",
    name: "Altın Kolye",
    displayName: "Altın Kolye",
    price: 18000,
    originalPrice: 18000,
    actualPrice: 12600,
    discountedPrice: 12600,
    secondPrice: 12600,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
  },
];
