export const featuredProducts = [
  {
    id: 1,
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    brand: "Ami Paris",
    name: "Siyah Organik Pamuk T-shirt",
    price: 11450,
  },
  {
    id: 2,
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    brand: "Beymen Club",
    name: "Comfort Fit Siyah Oxford Gömlek",
    price: 4499,
    discountedPrice: 3149.3,
    discountText: "Sepette %30",
  },
  {
    id: 3,
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    brand: "Beymen Club",
    name: "Comfort Fit Haki Oxford Gömlek",
    price: 4499,
    discountedPrice: 3149.3,
    discountText: "3 ve üzeri %30",
  },
  {
    id: 4,
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    brand: "Beymen Club",
    name: "Comfort Fit Haki Polo Sweatshirt",
    price: 5450,
    discountedPrice: 3815,
    discountText: "3 ve üzeri %30",
  },
  {
    id: 5,
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    brand: "Premium Collection",
    name: "Klasik Pırlanta Yüzük",
    price: 25000,
  },
  {
    id: 6,
    images: [
      "/product1.jpg",
      "/product2.jpg",
      "/product3.jpg",
      "/product4.jpg",
    ],
    brand: "Luxury Line",
    name: "Altın Kolye",
    price: 18000,
    discountedPrice: 12600,
    discountText: "Sepette %30",
  },
];
