import { Product } from "./ProductCard";

export const featuredProducts: Product[] = [
  {
    id: 1,
    productUrl: "/urun/1",
    images: [
      "/gorseller/urun1.jpg",
    ],
    image: "/gorseller/urun1.jpg",
    brand: "Gözümün Nuru",
    brandName: "Gözümün Nuru",
    name: "Işıltı Kolye",
    displayName: "Işıltı Kolye",
    price: 11450,
    actualPrice: 11450,
    originalPrice: 11450,
    hasDiscount: false,
  },
  {
    id: 2,
    productUrl: "/urun/2",
    images: [
      "/gorseller/urun2.jpg",
    ],
    image: "/gorseller/urun2.jpg",
    brand: "Gözümün Nuru",
    brandName: "Gözümün Nuru",
    name: "Zamansız Tektaş Yüzük",
    displayName: "Zamansız Tektaş Yüzük",
    price: 4499,
    originalPrice: 4499,
    actualPrice: 3149.3,
    discountedPrice: 3149.3,
    secondPrice: 3149.3,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
  },
  {
    id: 3,
    productUrl: "/urun/3",
    images: [
      "/gorseller/urun3.jpg",
    ],
    image: "/gorseller/urun3.jpg",
    brand: "Gözümün Nuru",
    brandName: "Gözümün Nuru",
    name: "Sonsuzluk Kolyesi",
    displayName: "Sonsuzluk Kolyesi",
    price: 4499,
    originalPrice: 4499,
    actualPrice: 3149.3,
    discountedPrice: 3149.3,
    secondPrice: 3149.3,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
    productPromotions: [
      {
        campaignTitle: "3 ve üzeri %30",
        promotedPrice: 3149.3,
        promotedPriceText: "3.149,30 ₺",
        showPrice: true,
      },
    ],
  },
  {
    id: 4,
    productUrl: "/urun/4",
    images: [
      "/gorseller/urun4.jpg",
    ],
    brand: "Gözümün Nuru",
    brandName: "Gözümün Nuru",
    name: "Luna Taşlı Küpe",
    displayName: "Luna Taşlı Küpe",
    price: 5450,
    originalPrice: 5450,
    actualPrice: 3815,
    discountedPrice: 3815,
    secondPrice: 3815,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
  },
  {
    id: 5,
    productUrl: "/urun/5",
    images: [
      "/gorseller/product2.avif",
    ],
    image: "/gorseller/product1.avif",
    brand: "Gözümün Nuru",
    brandName: "Gözümün Nuru",
    name: "Klasik Pırlanta Yüzük",
    displayName: "Klasik Pırlanta Yüzük",
    price: 25000,
    actualPrice: 25000,
    originalPrice: 25000,
    hasDiscount: false,
  },
  {
    id: 6,
    productUrl: "/urun/6",
    images: [
      "/gorseller/product3.avif",
    ],
    image: "/gorseller/product1.avif",
    brand: "Gözümün Nuru",
    brandName: "Gözümün Nuru",
    name: "Altın Kolye",
    displayName: "Altın Kolye",
    price: 18000,
    originalPrice: 18000,
    actualPrice: 12600,
    discountedPrice: 12600,
    secondPrice: 12600,
    hasDiscount: true,
    showDefaultDiscountRate: true,
    newDiscountRateText: "%30",
    discountRateText: "%30",
  },
];
